#!/bin/sh

set -xe

apk add linux-rpi linux-rpi4 raspberrypi-bootloader

echo "modules=loop,squashfs,sd-mod,usb-storage root=/dev/mmcblk0p2 rootfstype=ext4 fsck.repair=yes console=tty1 rootwait quiet cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory" > /boot/cmdline.txt

cat <<EOF > /boot/config.txt
[pi3]
gpu_mem=32
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi3+]
gpu_mem=32
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi4]
enable_gic=1
kernel=vmlinuz-rpi4
initramfs initramfs-rpi4
[all]
arm_64bit=1
include usercfg.txt
EOF

cat <<EOF > /boot/usercfg.txt
disable_overscan=1
dtparam=audio=on
dtoverlay=disable-bt
dtoverlay=iqaudio-dacplus,auto_mute_amp
EOF

# fstab
cat <<EOF > /etc/fstab
/dev/mmcblk0p1  /boot           vfat    defaults          0       2
/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1
EOF

cat <<EOF >> /etc/sysctl.conf
vm.vfs_cache_pressure=500
vm.swappiness=100
vm.dirty_background_ratio=1
vm.dirty_ratio=50
EOF
