#!/bin/sh

set -xe

TARGET_HOSTNAME="raspberrypi"
#TARGET_TIMEZONE="Europe/Zurich"
ROOT_PASS=raspberry

# base stuff
apk add curl ca-certificates
update-ca-certificates
echo "root:$ROOT_PASS" | chpasswd
setup-hostname $TARGET_HOSTNAME
echo "127.0.0.1    $TARGET_HOSTNAME $TARGET_HOSTNAME.localdomain" > /etc/hosts

# time
#apk add chrony tzdata
#setup-timezone -z $TARGET_TIMEZONE
