#!/bin/sh

set -xe

FIRST_USER_NAME=pi
FIRST_USER_PASS=raspberry

adduser -s /bin/ash -D $FIRST_USER_NAME

for GRP in adm dialout cdrom audio users video games input tty netdev; do
  adduser $FIRST_USER_NAME $GRP
done

echo "$FIRST_USER_NAME:$FIRST_USER_PASS" | chpasswd
